# Generated by Django 5.2 on 2025-04-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprocedure',
            old_name='procedure_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='serviceprocedure',
            name='procedure_notes',
        ),
    ]
