# Generated by Django 5.2.1 on 2025-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
