# Generated by Django 5.2.1 on 2025-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0002_nursingnotes_nurse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskfactor1',
            old_name='combined_oral',
            new_name='combined_oral_contraceptives_or_HRT',
        ),
        migrations.RenameField(
            model_name='riskfactor2',
            old_name='bed_72_hrs',
            new_name='patients_confinedto_bed_72_hrs',
        ),
        migrations.RenameField(
            model_name='riskfactor3',
            old_name='factor_V_leiden_or_activated',
            new_name='disordersof_plasminogen_and_plasminactivation',
        ),
        migrations.RenameField(
            model_name='riskfactor3',
            old_name='protein_C_resistance',
            new_name='factor_V_leiden_or_activated_protein_C_resistance',
        ),
        migrations.RenameField(
            model_name='riskfactor4',
            old_name='elective_major_lower',
            new_name='elective_major_lower_extremity',
        ),
        migrations.RenameField(
            model_name='riskfactor4',
            old_name='extremity',
            new_name='hip_pelvis_or_leg_fracture',
        ),
        migrations.RemoveField(
            model_name='riskfactor1',
            name='contraceptives_or_HRT',
        ),
        migrations.RemoveField(
            model_name='riskfactor2',
            name='patients_confined_to',
        ),
        migrations.RemoveField(
            model_name='riskfactor4',
            name='stroke_feedbackhip_pelvis_or_leg_fracture',
        ),
        migrations.AddField(
            model_name='riskfactor3',
            name='heparin_included_thrombocytopenia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskfactor3',
            name='hyperviscosity_syndromes',
            field=models.BooleanField(default=False),
        ),
    ]
