# Generated by Django 5.2.1 on 2025-06-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_rename_combined_oral_riskfactor1_combined_oral_contraceptives_or_hrt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialassessment',
            name='feedback_date',
        ),
    ]
