# Generated by Django 5.2 on 2025-05-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_alter_imaging_doctor_alter_labresult_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUsers',
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('pending', 'Pending')], default='processing', max_length=20),
        ),
    ]
