# Generated by Django 5.2 on 2025-06-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_remove_initialassessment_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentchart',
            name='hrs_drops_mins',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
