# Generated by Django 5.2 on 2025-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0005_delete_staffusers_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
