# Generated by Django 5.2.1 on 2025-06-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('rec_app', '0005_alter_treatmentchart_hrs_drops_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medication_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication'),
            preserve_default=False,
        ),
    ]
