# Generated by Django 5.2 on 2025-05-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0008_remove_imaging_doctor_remove_labresult_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabResult',
        ),
    ]
