# Generated by Django 5.2 on 2025-05-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0010_labresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imaging',
            name='patient',
        ),
        migrations.DeleteModel(
            name='LabResult',
        ),
        migrations.DeleteModel(
            name='Imaging',
        ),
    ]
