# Generated by Django 5.2 on 2025-05-28 09:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_Date', models.DateField(default=datetime.date.today)),
                ('Bill_No', models.CharField(blank=True, max_length=100, unique=True)),
                ('guest', models.BooleanField(default=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('doctor', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now_add=True)),
                ('typeof_transaction', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Debit/Credit', 'Debit/Credit'), ('UPI', 'UPI'), ('Multiple (Cash+Card), (Cash+UPI)', 'Multiple (Cash+Card), (Cash+UPI)')], max_length=50, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(max_length=100)),
                ('notification_created', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='p_invoice.pharmacyinvoice')),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication')),
            ],
        ),
    ]
