# Generated by Django 5.2.1 on 2025-06-25 04:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        ('pharmacy', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_value', models.CharField(blank=True, max_length=100, null=True)),
                ('Bill_Date', models.DateField(default=django.utils.timezone.now)),
                ('Bill_No', models.CharField(blank=True, max_length=100, unique=True)),
                ('guest', models.BooleanField(default=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('doctor', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now_add=True)),
                ('typeof_transaction', models.CharField(choices=[('Cash', 'Cash'), ('Debit/Credit', 'Debit/Credit'), ('UPI', 'UPI'), ('Multiple (Cash+Card), (Cash+UPI)', 'Multiple (Cash+Card), (Cash+UPI)')], max_length=50)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('notification_created', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('discount_requires_approval', models.BooleanField(default=False)),
                ('discount_approved', models.BooleanField(default=False)),
                ('discount_approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pharmacy_invoices', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='p_invoice.pharmacyinvoice')),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication')),
            ],
        ),
    ]
