# Generated by Django 5.2 on 2025-05-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyinvoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='pharmacyinvoiceitem',
            name='medication_name',
        ),
        migrations.DeleteModel(
            name='PharmacyInvoice',
        ),
        migrations.DeleteModel(
            name='PharmacyInvoiceItem',
        ),
    ]
