# Generated by Django 5.2.1 on 2025-05-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyinvoice',
            old_name='doctor_name',
            new_name='doctor',
        ),
    ]
