# Generated by Django 5.2.1 on 2025-06-09 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_invoice', '0003_initial'),
        ('patients', '0003_patient_last_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyinvoice',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='discount_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='discount_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pharmacy_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='discount_requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoice',
            name='Bill_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoice',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoice',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoice',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
