# Generated by Django 5.2.1 on 2025-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_invoice', '0004_remove_pharmacyinvoice_patient_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='patient_id_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
