# Generated by Django 5.2 on 2025-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_invoice', '0005_pharmacyinvoice_patient_id_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinvoice',
            name='typeof_transaction',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Debit/Credit', 'Debit/Credit'), ('UPI', 'UPI'), ('Multiple (Cash+Card), (Cash+UPI)', 'Multiple (Cash+Card), (Cash+UPI)')], default='Cash', max_length=50),
            preserve_default=False,
        ),
    ]
