# Generated by Django 5.2 on 2025-04-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_billing'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='billing',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
