# Generated by Django 5.2 on 2025-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_date_remove_patient_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
