# Generated by Django 5.2 on 2025-05-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='speciality',
            new_name='Department',
        ),
    ]
