# Generated by Django 5.2.1 on 2025-06-25 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_visits', models.IntegerField()),
                ('amount_per_visit', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('days', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('due_on_receipt', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('debit/credit', 'Debit/Credit'), ('multiple (cash+card), (cash+upi)', 'Multiple (Cash+Card), (Cash+UPI)'), ('insurance', 'Insurance'), ('government schemes', 'Government Schemes')], max_length=40)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
                ('concession', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('consultant', models.CharField(blank=True, max_length=30, null=True)),
                ('room_type', models.CharField(blank=True, max_length=20, null=True)),
                ('attendant_name', models.CharField(blank=True, max_length=30, null=True)),
                ('attendant_phno', models.CharField(blank=True, max_length=10, null=True)),
                ('admitted_date', models.DateField(blank=True, null=True)),
                ('discharged_date', models.DateField(blank=True, null=True)),
                ('care_type', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.consultationcharge')),
                ('investigation_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.investigationcharge')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('pharmacy_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice.pharmacycharge')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_service_charges', to='invoice.invoice')),
                ('service_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.servicecharge')),
            ],
            options={
                'unique_together': {('invoice', 'service_charge')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_charges',
            field=models.ManyToManyField(through='invoice.InvoiceServiceCharge', to='invoice.servicecharge'),
        ),
    ]
