# Generated by Django 5.2.1 on 2025-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('debit/credit', 'Debit/Credit'), ('multiple (cash+card), (cash+upi)', 'Multiple (Cash+Card), (Cash+UPI)'), ('insurance', 'Insurance'), ('government schemes', 'Government Schemes')], max_length=40),
        ),
    ]
