# Generated by Django 5.2 on 2025-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_concession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationcharge',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigationcharge',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacycharge',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacycharge',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
