# Generated by Django 5.2.1 on 2025-06-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_admitted_date_invoice_attendant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='referral_doctor',
        ),
    ]
