# Generated by Django 5.2.1 on 2025-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default='INV001', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
