# Generated by Django 5.2 on 2025-06-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_investigationcharge_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
