# Generated by Django 5.2.1 on 2025-06-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_referral_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='admitted_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='attendant_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='attendant_phno',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='care_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discharged_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='room_type',
        ),
    ]
