# Generated by Django 5.2.1 on 2025-05-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('low_stock', 'Low Stock'), ('expiry', 'Expiry Alert'), ('stagnant', 'Stagnant Drug'), ('medication_add', 'Medication Added'), ('lab_invoice', 'Lab Invoice'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('invoice', 'Invoice'), ('sales', 'Sales')], max_length=50),
        ),
    ]
