# Generated by Django 5.2.1 on 2025-05-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('p_invoice', '0002_rename_doctor_name_pharmacyinvoice_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pharmacy_invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='p_invoice.pharmacyinvoiceitem'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
