# Generated by Django 5.2.1 on 2025-05-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_invoice_and_more'),
    ]

    operations = [
    ]
