# Generated by Django 5.2 on 2025-05-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
