# Generated by Django 5.2.1 on 2025-05-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_investigationcharge_from_date_and_more'),
        ('notifications', '0005_initial'),
        ('p_invoice', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='p_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_notifications', to='p_invoice.pharmacyinvoice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_notifications', to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('low_stock', 'Low Stock'), ('expiry', 'Expiry Alert'), ('stagnant', 'Stagnant Drug'), ('medication_add', 'Medication Added'), ('lab_invoice', 'Lab Invoice'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('invoice', 'Invoice'), ('sales', 'Sales'), ('bills', 'Bills')], max_length=50),
        ),
    ]
