# Generated by Django 5.2.1 on 2025-06-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_entered_by_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
