# Generated by Django 5.2.1 on 2025-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_notification_entered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for discount approval notifications', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient_id_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('low_stock', 'Low Stock'), ('expiry', 'Expiry Alert'), ('stagnant', 'Stagnant Drug'), ('medication_add', 'Medication Added'), ('lab_invoice', 'Lab Invoice'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('invoice', 'Invoice'), ('sales', 'Sales'), ('bills', 'Bills'), ('discount_approval', 'Discount Approval')], max_length=50),
        ),
    ]
