# Generated by Django 5.2.1 on 2025-06-25 11:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(help_text='Enter the test name (e.g., Blood Test)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount charged for the test', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('in Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the invoice', max_length=15)),
                ('date', models.DateField(default=datetime.date.today, help_text='Date of invoice creation')),
                ('patient', models.ForeignKey(help_text='Select a patient that exists in the Patient database', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_test', models.CharField(max_length=100)),
                ('request_date', models.DateField(help_text='Date when test was requested')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inProgress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for additional information', null=True)),
                ('test_date', models.DateField(help_text='Date when test is performed')),
                ('test_time', models.TimeField(help_text='Time when test is performed')),
                ('summary', models.TextField(blank=True, help_text='Summary or interpretation of test result', null=True)),
                ('test_type', models.CharField(help_text='Category/type of test (e.g., Hematology, Radiology)', max_length=100)),
                ('upload', models.FileField(blank=True, help_text='Single file upload for test report or images', null=True, upload_to='labtest_uploads/')),
                ('flag', models.BooleanField(default=False, help_text='Boolean flag for internal logic (e.g., mark for review)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient')),
                ('request_by', models.ForeignKey(blank=True, help_text='User who requested the test (taken from login credentials)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
