# Generated by Django 5.2 on 2025-05-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabInvoice',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
    ]
