# Generated by Django 5.2.1 on 2025-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_labinvoice_status_alter_labtest_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinvoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the invoice', max_length=15),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=15),
        ),
    ]
