# Generated by Django 5.2.1 on 2025-06-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_alter_labinvoice_status_alter_labtest_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinvoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('in Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the invoice', max_length=15),
        ),
    ]
