# Generated by Django 5.2 on 2025-04-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ward_no',
        ),
    ]
